packageExtensions:
  react-error-boundary@*:
    dependencies:
      prop-types: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  debug@*:
    peerDependencies:
      supports-color: "*"
  next@*:
    dependencies:
      eslint-import-resolver-node: "*"


yarnPath: .yarn/releases/yarn-3.0.0.cjs
