compressionLevel: mixed

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  next@*:
    dependencies:
      eslint-import-resolver-node: "*"
  react-error-boundary@*:
    dependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
