blank_issues_enabled: false
contact_links:
  - name: "💬 Support: Slack"
    url: https://join.slack.com/t/slate-js/shared_invite/zt-f8t986ip-7dA1DyiqPpzootz1snKXkw
    about: Please ask and answer questions in our Slack channel.
