# https://github.com/marketplace/actions/automatic-rebase  (https://github.com/cirrus-actions/rebase)
name: Comment

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read # to fetch code (actions/checkout)
  pull-requests: read # to get info about PR (cirrus-actions/rebase)

jobs:
  rebase:
    permissions:
      contents: write # to push code to rebase (cirrus-actions/rebase)
      pull-requests: read # to get info about PR (cirrus-actions/rebase)

    name: rebase
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association) &&
      startsWith(github.event.comment.body, '/rebase')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Rebase PR
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

